---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    groups:
      - etcd
      - vtgate
      - vitess_build
    image: centos:8
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
provisioner:
  name: ansible
  inventory:
    host_vars:
      instance:
        enable_vtgate: False
verifier:
  name: ansible
