- name: install config
  become: yes
  become_user: root
  register: vtgate_service_modified
  with_items:
    - s: vtgate.conf
      d: '/etc/vitess/conf/vtgate-{{ gateway.id }}.conf'
  template:
    src: '{{ item.s }}.j2'
    dest: '{{ item.d }}'
    owner: '{{ vitess_user }}'
    group: '{{ vitess_group }}'
    mode: '0644'
  notify:
    - restart vtgate

- name: start vtgate
  become: yes
  become_user: root
  when:
    - enable_vtgate | bool
  service:
    name: 'vtgate@{{ gateway.id }}'
    enabled: yes
    state: started
  changed_when: false
